### ISSUE TITLE
post-export.py broken when spaces present in hard drive name

### ISSUE THREAD

**Issue by okhick** [Cycling74/gen-plugin-export#2]
I'm attempting to export the example project but I'm getting an unusual error. The Max console prints out `sh: /Volumes/Macintosh: No such file or directory`. When I run the script via the terminal on MacOS, I get a different set of errors: 

`The files /Volumes/Macintosh and /Volumes/Macintosh HD/Downloads/gen-plugin-export-master/HD/Downloads/gen-plugin-export-master/Introjucer/Introjucer.app do not exist.
/usr/bin/xcodebuild -project /Volumes/Macintosh HD/Downloads/gen-plugin-export-master/VST-Builds/MacOSX/C74-Gen-VSTPlugin.xcodeproj -configuration Debug
xcodebuild: error: Unknown build action 'HD/Downloads/gen-plugin-export-master/VST-Builds/MacOSX/C74-Gen-VSTPlugin.xcodeproj'`.

For starters, my drive is called Macintosh HD, not just Macintosh. I can't figure out why the rest of the name is getting cut off. Secondly, I'm attempting to create and AU. I've changed the augment in the Max attribute box and made sure that the necessary CoreAudio files are in place. I've poked around a bit within the python script but I can't seem to gain any ground. 

For reference, here's the entire terminal printout: 
`$ python post-export.py
NO TEMP INTROJUCER PROJECT FOUND
WRITING TEMP INTROJUCER PROJECT
darwin
open -n /Volumes/Macintosh HD/Downloads/gen-plugin-export-master/Introjucer/Introjucer.app  --args --resave "/Volumes/Macintosh HD/Downloads/gen-plugin-export-master/Introjucer/tmp-C74-Gen-VSTPlugin.jucer"
The files /Volumes/Macintosh and /Volumes/Macintosh HD/Downloads/gen-plugin-export-master/HD/Downloads/gen-plugin-export-master/Introjucer/Introjucer.app do not exist.
/usr/bin/xcodebuild -project /Volumes/Macintosh HD/Downloads/gen-plugin-export-master/VST-Builds/MacOSX/C74-Gen-VSTPlugin.xcodeproj -configuration Debug
xcodebuild: error: Unknown build action 'HD/Downloads/gen-plugin-export-master/VST-Builds/MacOSX/C74-Gen-VSTPlugin.xcodeproj'.`

**Comment by tap** [comment]
It does indeed sound like the space in the hard-drive name is throwing it off. I'm not sure if changing the name of the hard drive is a tenable solution / work-around, but it might at least prove or disprove this theory.

**Comment by okhick** [comment]
I think your theory is correct. I was able to briefly change my HD name and the export seemed to work better. Changing the name messed up application authorization (among other things) and the script hung when trying to open Introjucer, but I saw messages on the console that I've never seen before. 

My python skills are not strong so any pointers on where to start fixing this would be much appreciated. 

Also FWIW, I just discovered the Juce5 branch and has switched over to that.

**Comment by okhick** [comment]
I just ran the process from a flash drive and it worked! Confirming the space in the name is an issue and finding an acceptable work around for the time being.

**Comment by tap** [comment]
Thanks for confirming @okhick. 

I am limited in my Python skills, but I'll take a look at it unless @jeremybernstein or @cccstbccc would rather take it.

**Comment by isabelgk** [comment]
Resolved in latest major update
